language: node_js

matrix:
  include:
    - node_js: '8'
    - node_js: '9' 
    - node_js: '10'
    - node_js: '11'
    - node_js: '12'
    - node_js: '13'
    - node_js: '14'
    - node_js: '15'
    - node_js: '16'

# cache: yarn

env:
  global:
    - TRAVIS=true

before_script:
  - rm -rf package-lock.json
  - rm -rf yarn.lock
  - rm -rf node_modules
  - ls -la
  - yarn add express inspc jest@26.6.3
  
script:
  - /bin/bash test.sh

after_script:
  - bash <(curl -s https://codecov.io/bash)



