language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16

# cache: yarn

env:
  global:
    - TRAVIS=true

before_script:
  - ls -la
  - rm -rf package-lock.json
  - rm -rf yarn.lock
  - rm -rf node_modules
  - yarn add express inspc jest nlab
  
script:
  - /bin/bash test.sh

after_script:
  - bash <(curl -s https://codecov.io/bash)



