language: node_js
node_js:
  - 16
#dist: trusty

#node_js: '10'
#  - '8'
#  - '9'
#  - '10'
#  - '11'

# matrix:
#   include:
# #     - node_js: '8'
# #       env: MODE=jest
# #       dist: trusty
# # #    - node_js: '9' # jest dep error: sane@3.1.0: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*"
# # #      env: MODE=jest
# # #      dist: trusty
# #     - node_js: '10'
# #       env: MODE=jest
# #       dist: trusty
# #     - node_js: '11'
# #       env: MODE=jest
# #       dist: trusty
# #     - node_js: '12'
# #       env: MODE=jest
# #       dist: trusty
# #     - node_js: '13'
# #       env: MODE=jest
# #       dist: trusty
#     - node_js: '16'

#       env: MODE=jest
#       dist: trusty

# https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
# branches:
#   except:
#     - master

cache: yarn

env:
  global:
    - TRAVIS=true

before_script:
  - make yarn
# #  - yarn add "coveralls"@"^3.0.2" "jest"@"^23.6.0"
#   - sudo apt-get install tree || true
#   - tree test || true

script:
  - /bin/bash test.sh

#after_success:
#  - cat ./coverage/lcov.info | node node_modules/coveralls/bin/coveralls.js

after_script:
  - bash <(curl -s https://codecov.io/bash)



